03-button add buttons
js-tasks-ru/htmlcss-20220317_nataliya-kokoreva pull request #3
Opened 2022-03-28 13:06 UTC by Athalie

2022-03-28 13:06 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-28 13:10 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-03-28 13:10 UTC, GSemikozov requested changes

2022-03-28 13:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "../../assets/css/main.css";
не нужно импортировать другие стили в файл стилей компонента. Наоборот - main.css содержит в себе все стили (в тч глобальные), которые и подключаются на страницу

2022-03-28 13:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-top: 14px;
слева-справа тоже надо)

2022-03-28 13:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-top: 14px;
по дизайну если быть точном здесь 15

2022-03-28 13:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
min значение здесь не нужно указывать

2022-03-28 13:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
указывает сразу на .button

2022-03-28 13:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.btn-primary {
модификаторы записываем через одно нижнее подчеркивание

2022-03-28 13:18 UTC, Athalie commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
А случай с ресайзом, когда плющим кнопку по максимуму, решаем за счет padding'ов?

2022-03-28 13:19 UTC, Athalie commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
Не поняла - указать на элементе button? Просто у меня главный класс кнопки - .btn

2022-03-28 13:21 UTC, Athalie commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
Аналогично и насчет ширины - убираем минимум, потому что расчет на padding'и?

2022-03-28 13:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-03-29 19:37 UTC, GSemikozov requested changes

2022-03-29 19:37 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
да, на .btn

2022-03-29 19:37 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-right: 57px;
у secondary не стоит менять паддинги - в этом плане все 3 типа одинаковы

2022-03-29 19:37 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-right: 62px;
и тут не нужно менять паддинги

2022-03-29 19:37 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    box-sizing: border-box;
можно указать сразу на .btn

2022-03-30 08:02 UTC, Athalie commented on 03-lection1/01-button/button.css
> +    padding-right: 57px;
Не могу понять - в макете разные паддинги. За счет чего в итоге кнопки одинаково будут выглядеть?

2022-03-30 08:04 UTC, Athalie commented on 03-lection1/01-button/button.css
> +    padding-right: 57px;
И если все у всех одинаково - то вешать паддинги на класс .btn ?

2022-03-30 19:08 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    min-height: 48px;
да, ширину фиксировать не надо, слева-справа будет паддинг которые не даст текст приклеиваться к границам кнопки

2022-03-30 19:10 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-right: 57px;
разные потому, что текст внутри кнопок разной длины. Но это на самом деле не паддинги, а реальные отступы от текста до границы блока. А паддинг - это внутренний отступ у кнопки, который не дает возможности тексту приклеиваться к к границам кнопки, и паддинги у всех типов кнопок одинаковые

2022-03-31 15:25 UTC, GSemikozov approved these changes

2022-03-31 15:25 UTC, merged